# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-30 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
